kind: PersistentVolume
apiVersion: v1
metadata:
  name: example-pv
spec:
  capacity:
    stprage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce '
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /mnt/disks/vol1
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernets.io/hostname
              operator: In
              values:
                - node-1